In [1]:
import pandas as pd

In [15]:
df = pd.read_csv("s3://rwc-ml-datasets/raw/Flight_Delay_Prediction_Datasets/weather_data/weather_batch_291.csv.gz", compression="gzip")

In [16]:
df.head()

,station,valid,tmpf,dwpf,relh,sknt,gust,vsby,skyc1,skyc2,skyc3,wxcodes,p01i,alti
0,BDL,2025-01-01 00:51,42.00,32.00,67.42,3.00,M,10.00,BKN,BKN,M,M,0.00,29.80
1,CLT,2025-01-01 00:52,59.00,48.00,66.83,9.00,M,10.00,FEW,M,M,M,0.00,29.66
2,ABQ,2025-01-01 00:52,48.00,17.00,28.69,3.00,M,10.00,CLR,M,M,M,0.00,30.06
3,PBG,2025-01-01 00:53,40.00,30.00,67.18,5.00,M,10.00,CLR,M,M,M,0.00,29.78
4,MCI,2025-01-01 00:53,31.00,24.00,74.97,10.00,M,10.00,OVC,M,M,M,0.00,30.19

In [17]:
df.tail()

,station,valid,tmpf,dwpf,relh,sknt,gust,vsby,skyc1,skyc2,skyc3,wxcodes,p01i,alti
261113,LRD,2025-12-31 23:56,66.00,19.00,16.32,6.00,M,10.00,CLR,M,M,M,0.00,30.17
261114,SDF,2025-12-31 23:56,38.00,29.00,69.72,12.00,M,10.00,OVC,M,M,M,0.00,29.95
261115,BIH,2025-12-31 23:56,45.00,30.00,55.41,9.00,M,10.00,OVC,M,M,-RA,T,30.13
261116,HYS,2025-12-31 23:56,52.00,22.00,30.59,7.00,M,10.00,CLR,M,M,M,0.00,30.00
261117,FLG,2025-12-31 23:57,41.00,31.00,67.29,0.00,M,10.00,BKN,OVC,M,M,T,30.26

In [18]:
df.shape

(261118, 14)

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 261118 entries, 0 to 261117
Data columns (total 14 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   station  261118 non-null  str
 1   valid    261118 non-null  str
 2   tmpf     261118 non-null  str
 3   dwpf     261118 non-null  str
 4   relh     261118 non-null  str
 5   sknt     261118 non-null  str
 6   gust     261118 non-null  str
 7   vsby     261118 non-null  str
 8   skyc1    261118 non-null  str
 9   skyc2    261118 non-null  str
 10  skyc3    261118 non-null  str
 11  wxcodes  261118 non-null  str
 12  p01i     261118 non-null  str
 13  alti     261118 non-null  str
dtypes: str(14)
memory usage: 43.0 MB